SELECT T1.CUS_GENDER, COUNT(T1.CUS_ID) NUMBER_OF_CUSTOMERS FROM 
(SELECT DISTINCT B.CUS_GENDER, B.CUS_ID
FROM `order` A, customer B
WHERE 
A.CUS_ID = B.CUS_ID
AND A.ORD_AMOUNT>=3000) AS T1
GROUP BY T1.CUS_GENDER;