INSERT INTO supplier (SUPP_NAME, SUPP_CITY, SUPP_PHONE) VALUES ('RAJESH RETAILS','DELHI','1234567890');
INSERT INTO supplier (SUPP_NAME, SUPP_CITY, SUPP_PHONE) VALUES ('APPARIO LTD.','MUMBAI','2589631470');
INSERT INTO supplier (SUPP_NAME, SUPP_CITY, SUPP_PHONE) VALUES ('KNOME PRODUCTS','BANGLORE','9785462315');
INSERT INTO supplier (SUPP_NAME, SUPP_CITY, SUPP_PHONE) VALUES ('BANSAL RETAILS','KOCHI','8975463285');
INSERT INTO supplier (SUPP_NAME, SUPP_CITY, SUPP_PHONE) VALUES ('MITTAL LTD.','LUCKNOW','7898456532');
