insert into supplier_pricing (PRO_ID, SUPP_ID, SUPP_PRICE) values ((select pro_id from product where pro_name = 'ROG LAPTOP'),(select supp_id from supplier where supp_name ='Mittal Ltd.'),30000);
insert into supplier_pricing (PRO_ID, SUPP_ID, SUPP_PRICE) values ((select pro_id from product where pro_name = 'GTA V'),(select supp_id from supplier where supp_name ='Appario Ltd.'),1500);
insert into supplier_pricing (PRO_ID, SUPP_ID, SUPP_PRICE) values ((select pro_id from product where pro_name = 'ROG LAPTOP'),(select supp_id from supplier where supp_name ='Mittal Ltd.'),30000);
insert into supplier_pricing (PRO_ID, SUPP_ID, SUPP_PRICE) values ((select pro_id from product where pro_name = 'HARRY POTTER'),(select supp_id from supplier where supp_name ='Rajesh Retails'),3000);
insert into supplier_pricing (PRO_ID, SUPP_ID, SUPP_PRICE) values ((select pro_id from product where pro_name = 'TSHIRT'),(select supp_id from supplier where supp_name ='Knome products'),2500);
insert into supplier_pricing (PRO_ID, SUPP_ID, SUPP_PRICE) values ((select pro_id from product where pro_name = 'OATS'),(select supp_id from supplier where supp_name ='Rajesh Retails'),1000);
insert into supplier_pricing (PRO_ID, SUPP_ID, SUPP_PRICE) values ((select pro_id from product where pro_name = 'Train Your Brain'),(select supp_id from supplier where supp_name ='Appario Ltd.'),780);
insert into supplier_pricing (PRO_ID, SUPP_ID, SUPP_PRICE) values ((select pro_id from product where pro_name = 'Train Your Brain'),(select supp_id from supplier where supp_name ='Bansal Retails'),789);
insert into supplier_pricing (PRO_ID, SUPP_ID, SUPP_PRICE) values ((select pro_id from product where pro_name = 'ROG LAPTOP'),(select supp_id from supplier where supp_name ='Rajesh Retails'),31000);
insert into supplier_pricing (PRO_ID, SUPP_ID, SUPP_PRICE) values ((select pro_id from product where pro_name = 'GTA V'),(select supp_id from supplier where supp_name ='Mittal Ltd.'),1450);
insert into supplier_pricing (PRO_ID, SUPP_ID, SUPP_PRICE) values ((select pro_id from product where pro_name = 'OATS'),(select supp_id from supplier where supp_name ='Appario Ltd.'),999);
insert into supplier_pricing (PRO_ID, SUPP_ID, SUPP_PRICE) values ((select pro_id from product where pro_name = 'Boat Earphones'),(select supp_id from supplier where supp_name ='Knome products'),549);
insert into supplier_pricing (PRO_ID, SUPP_ID, SUPP_PRICE) values ((select pro_id from product where pro_name = 'Boat Earphones'),(select supp_id from supplier where supp_name ='Bansal Retails'),529);
insert into supplier_pricing (PRO_ID, SUPP_ID, SUPP_PRICE) values ((select pro_id from product where pro_name = 'MILK'),(select supp_id from supplier where supp_name ='Appario Ltd.'),105);
insert into supplier_pricing (PRO_ID, SUPP_ID, SUPP_PRICE) values ((select pro_id from product where pro_name = 'MILK'),(select supp_id from supplier where supp_name ='Rajesh Retails'),99);
insert into supplier_pricing (PRO_ID, SUPP_ID, SUPP_PRICE) values ((select pro_id from product where pro_name = 'TSHIRT'),(select supp_id from supplier where supp_name ='Mittal Ltd.'),2999);
insert into supplier_pricing (PRO_ID, SUPP_ID, SUPP_PRICE) values ((select pro_id from product where pro_name = 'HARRY POTTER'),(select supp_id from supplier where supp_name ='Appario Ltd.'),2999);
