CREATE TABLE IF NOT EXISTS  supplier_pricing(
PRICING_ID	INT PRIMARY KEY  AUTO_INCREMENT,
PRO_ID	INT,
SUPP_ID	INT,
SUPP_PRICE	INT DEFAULT 0,
FOREIGN KEY (PRO_ID) REFERENCES product (PRO_ID),
FOREIGN KEY (SUPP_ID) REFERENCES supplier (SUPP_ID)
);